[workspace]
members = [
    "h3",
    "h3-quinn",
    "h3-webtransport",

    # Internal
    "examples",
]
resolver = "2"

[patch.crates-io]
quinn = { git = "https://github.com/mxinden/quinn.git", branch = "reproduce-2041" }
